-- ============================================================
-- LoanFlow Database Schema
-- ============================================================

-- ── Sequences for human-readable business keys ──────────────
CREATE SEQUENCE IF NOT EXISTS application_number_seq START 1 INCREMENT 1;
CREATE SEQUENCE IF NOT EXISTS loan_number_seq        START 1 INCREMENT 1;
CREATE SEQUENCE IF NOT EXISTS payment_receipt_seq    START 1 INCREMENT 1;

-- -- ── Users (base table, joined-table inheritance) ─────────────
-- CREATE TABLE IF NOT EXISTS users (
--                                      id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--                                      dtype         VARCHAR(20)  NOT NULL,
--     name          VARCHAR(255) NOT NULL,
--     email         VARCHAR(255) NOT NULL UNIQUE,
--     password      VARCHAR(255) NOT NULL,
--     phone         VARCHAR(15)  NOT NULL,
--     role          VARCHAR(30)  NOT NULL,
--     is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
--     is_deleted    BOOLEAN      NOT NULL DEFAULT FALSE,
--     deleted_at    TIMESTAMP,
--     last_login_at TIMESTAMP,
--     created_at    TIMESTAMP    NOT NULL,
--     created_by    VARCHAR(255),
--     updated_at    TIMESTAMP    NOT NULL,
--     updated_by    VARCHAR(255),
--     version       BIGINT
--     );
--
-- -- ── Borrower (joined subtype of users) ──────────────────────
-- CREATE TABLE IF NOT EXISTS borrower (
--                                         id             BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
--     pan_number     VARCHAR(20)     NOT NULL UNIQUE,
--     date_of_birth  DATE            NOT NULL,
--     occupation     VARCHAR(255)    NOT NULL,
--     monthly_income NUMERIC(15, 2)  NOT NULL,
--     address_id     BIGINT
--     );
--
-- -- ── Loan Officers (joined subtype of users) ──────────────────
-- CREATE TABLE IF NOT EXISTS loan_officers (
--                                              id            BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
--     employee_id   VARCHAR(50) UNIQUE,
--     department    VARCHAR(100)
--     );
--
-- -- ── Admins (joined subtype of users) ─────────────────────────
-- CREATE TABLE IF NOT EXISTS admins (
--                                       id           BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
--     access_level VARCHAR(30)
--     );
--
-- -- ── Address ──────────────────────────────────────────────────
-- CREATE TABLE IF NOT EXISTS addresses (
--                                          id           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--                                          street       VARCHAR(255),
--     city         VARCHAR(100),
--     state        VARCHAR(100),
--     pincode      VARCHAR(10),
--     country      VARCHAR(100),
--     created_at   TIMESTAMP NOT NULL,
--     created_by   VARCHAR(255),
--     updated_at   TIMESTAMP NOT NULL,
--     updated_by   VARCHAR(255),
--     version      BIGINT
--     );
--
-- ALTER TABLE borrower
--     ADD CONSTRAINT IF NOT EXISTS fk_borrower_address
--     FOREIGN KEY (address_id) REFERENCES addresses(id);
--
-- -- ── Loan Applications ─────────────────────────────────────────
-- CREATE TABLE IF NOT EXISTS loan_applications (
--                                                  id                   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--                                                  application_number   VARCHAR(20)    NOT NULL UNIQUE,
--     borrower_id          BIGINT         NOT NULL REFERENCES users(id),
--     reviewed_by          BIGINT         REFERENCES users(id),
--     requested_amount     NUMERIC(15, 2) NOT NULL,
--     tenure_months        INTEGER        NOT NULL,
--     monthly_income       NUMERIC(15, 2) NOT NULL,
--     existing_monthly_emi NUMERIC(15, 2) NOT NULL DEFAULT 0,
--     calculated_dti       NUMERIC(5, 2),
--     bureau_status        VARCHAR(20),
--     suggested_strategy   VARCHAR(30),
--     final_strategy       VARCHAR(30),
--     status               VARCHAR(30)    NOT NULL DEFAULT 'PENDING',
--     rejection_reason     VARCHAR(500),
--     reviewed_at          TIMESTAMP,
--     created_at           TIMESTAMP      NOT NULL,
--     created_by           VARCHAR(255),
--     updated_at           TIMESTAMP      NOT NULL,
--     updated_by           VARCHAR(255),
--     version              BIGINT
--     );
--
-- CREATE INDEX IF NOT EXISTS idx_loan_application_number ON loan_applications(application_number);
-- CREATE INDEX IF NOT EXISTS idx_app_borrower            ON loan_applications(borrower_id);
-- CREATE INDEX IF NOT EXISTS idx_app_status              ON loan_applications(status);
--
-- -- ── Loans ─────────────────────────────────────────────────────
-- CREATE TABLE IF NOT EXISTS loans (
--                                      id                      BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--                                      loan_number             VARCHAR(30)    NOT NULL UNIQUE,
--     application_id          BIGINT         NOT NULL UNIQUE REFERENCES loan_applications(id),
--     borrower_id             BIGINT         NOT NULL REFERENCES users(id),
--     approved_by             BIGINT         NOT NULL REFERENCES users(id),
--     approved_amount         NUMERIC(15, 2) NOT NULL,
--     interest_rate_per_annum NUMERIC(5, 2)  NOT NULL,
--     tenure_months           INTEGER        NOT NULL,
--     strategy                VARCHAR(30)    NOT NULL,
--     monthly_emi             NUMERIC(15, 2) NOT NULL,
--     outstanding_principal   NUMERIC(15, 2) NOT NULL,
--     over_due_count          INTEGER        NOT NULL DEFAULT 0,
--     status                  VARCHAR(30)    NOT NULL DEFAULT 'ACTIVE',
--     disbursed_at            TIMESTAMP,
--     closed_at               TIMESTAMP,
--     created_at              TIMESTAMP      NOT NULL,
--     created_by              VARCHAR(255),
--     updated_at              TIMESTAMP      NOT NULL,
--     updated_by              VARCHAR(255),
--     version                 BIGINT
--     );
--
-- CREATE INDEX IF NOT EXISTS idx_loan_number   ON loans(loan_number);
-- CREATE INDEX IF NOT EXISTS idx_loan_borrower ON loans(borrower_id);
-- CREATE INDEX IF NOT EXISTS idx_loan_status   ON loans(status);
--
-- -- ── EMI Schedules ─────────────────────────────────────────────
-- CREATE TABLE IF NOT EXISTS emi_schedules (
--                                              id                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--                                              loan_id            BIGINT         NOT NULL REFERENCES loans(id) ON DELETE CASCADE,
--     installment_number INTEGER        NOT NULL,
--     due_date           DATE           NOT NULL,
--     principal_amount   NUMERIC(15, 2) NOT NULL,
--     interest_amount    NUMERIC(15, 2) NOT NULL,
--     total_emi_amount   NUMERIC(15, 2) NOT NULL,
--     remaining_balance  NUMERIC(15, 2) NOT NULL,
--     status             VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
--     paid_at            TIMESTAMP,
--     created_at         TIMESTAMP      NOT NULL,
--     created_by         VARCHAR(255),
--     updated_at         TIMESTAMP      NOT NULL,
--     updated_by         VARCHAR(255),
--     version            BIGINT
--     );
--
-- CREATE INDEX IF NOT EXISTS idx_emi_loan     ON emi_schedules(loan_id);
-- CREATE INDEX IF NOT EXISTS idx_emi_due_date ON emi_schedules(due_date);
-- CREATE INDEX IF NOT EXISTS idx_emi_status   ON emi_schedules(status);
--
-- -- ── Payments ─────────────────────────────────────────────────
-- CREATE TABLE IF NOT EXISTS payments (
--                                         id              BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--                                         receipt_number  VARCHAR(30)    NOT NULL UNIQUE,
--     emi_schedule_id BIGINT         NOT NULL UNIQUE REFERENCES emi_schedules(id),
--     loan_id         BIGINT         NOT NULL REFERENCES loans(id),
--     borrower_id     BIGINT         NOT NULL REFERENCES users(id),
--     paid_amount     NUMERIC(15, 2) NOT NULL,
--     payment_mode    VARCHAR(30)    NOT NULL DEFAULT 'SIMULATION',
--     paid_at         TIMESTAMP      NOT NULL,
--     created_at      TIMESTAMP      NOT NULL,
--     created_by      VARCHAR(255),
--     updated_at      TIMESTAMP      NOT NULL,
--     updated_by      VARCHAR(255),
--     version         BIGINT
--     );
--
-- CREATE UNIQUE INDEX IF NOT EXISTS idx_receipt_number ON payments(receipt_number);
--
-- -- ── Overdue Tracker ───────────────────────────────────────────
-- CREATE TABLE IF NOT EXISTS overdue_tracker (
--                                                id                   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--                                                emi_schedule_id      BIGINT         NOT NULL UNIQUE REFERENCES emi_schedules(id),
--     loan_id              BIGINT         NOT NULL REFERENCES loans(id),
--     borrower_id          BIGINT         NOT NULL REFERENCES users(id),
--     due_date             DATE           NOT NULL,
--     fixed_penalty_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
--     penalty_rate         NUMERIC(5, 2)  NOT NULL DEFAULT 0,
--     penalty_charge       NUMERIC(5, 2)  NOT NULL DEFAULT 0,
--     penalty_status       VARCHAR(20),
--     days_overdue         INTEGER        NOT NULL DEFAULT 0,
--     alert_count          INTEGER        NOT NULL DEFAULT 0,
--     detected_at          TIMESTAMP      NOT NULL,
--     last_alert_at        TIMESTAMP,
--     resolved_at          TIMESTAMP,
--     created_at           TIMESTAMP      NOT NULL,
--     created_by           VARCHAR(255),
--     updated_at           TIMESTAMP      NOT NULL,
--     updated_by           VARCHAR(255),
--     version              BIGINT
--     );
--
-- CREATE INDEX IF NOT EXISTS idx_overdue_alert ON overdue_tracker(last_alert_at, resolved_at);
--
-- -- ── Loan Status History ───────────────────────────────────────
-- CREATE TABLE IF NOT EXISTS loan_status_history (
--                                                    id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--                                                    loan_id    BIGINT      NOT NULL REFERENCES loans(id) ON DELETE CASCADE,
--     old_status VARCHAR(30) NOT NULL,
--     new_status VARCHAR(30) NOT NULL,
--     changed_by BIGINT      REFERENCES users(id),
--     reason     VARCHAR(500),
--     changed_at TIMESTAMP   NOT NULL,
--     created_at TIMESTAMP   NOT NULL,
--     created_by VARCHAR(255),
--     updated_at TIMESTAMP   NOT NULL,
--     updated_by VARCHAR(255),
--     version    BIGINT
--     );
--
-- CREATE INDEX IF NOT EXISTS idx_lsh_loan ON loan_status_history(loan_id);
--
-- -- ── Notifications ─────────────────────────────────────────────
-- CREATE TABLE IF NOT EXISTS notifications (
--                                              id             BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--                                              recipient_id   BIGINT       NOT NULL REFERENCES users(id),
--     loan_id        BIGINT       REFERENCES loans(id),
--     destination    VARCHAR(255) NOT NULL,
--     event_type     VARCHAR(50)  NOT NULL,
--     status         VARCHAR(20)  NOT NULL DEFAULT 'QUEUED',
--     subject        VARCHAR(255) NOT NULL,
--     content        TEXT         NOT NULL,
--     retry_count    INTEGER      NOT NULL DEFAULT 0,
--     failure_reason VARCHAR(500),
--     scheduled_at   TIMESTAMP,
--     sent_at        TIMESTAMP,
--     created_at     TIMESTAMP    NOT NULL,
--     created_by     VARCHAR(255),
--     updated_at     TIMESTAMP    NOT NULL,
--     updated_by     VARCHAR(255),
--     version        BIGINT
--     );
--
-- CREATE INDEX IF NOT EXISTS idx_notif_status ON notifications(status);
-- CREATE INDEX IF NOT EXISTS idx_notif_retry  ON notifications(retry_count);
--
-- -- ── Audit Logs ────────────────────────────────────────────────
-- CREATE TABLE IF NOT EXISTS audit_logs (
--                                           id                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--                                           entity_type        VARCHAR(50)  NOT NULL,
--     entity_id          BIGINT       NOT NULL,
--     action             VARCHAR(50)  NOT NULL,
--     old_status         VARCHAR(30),
--     new_status         VARCHAR(30),
--     change_detail_json TEXT,
--     performed_by       BIGINT       REFERENCES users(id),
--     actor_role         VARCHAR(20)  NOT NULL,
--     remarks            VARCHAR(1000),
--     created_at         TIMESTAMP    NOT NULL DEFAULT NOW()
--     );
--
-- CREATE INDEX IF NOT EXISTS idx_audit_entity     ON audit_logs(entity_type, entity_id);
-- CREATE INDEX IF NOT EXISTS idx_audit_actor_role ON audit_logs(actor_role);
-- CREATE INDEX IF NOT EXISTS idx_audit_created_at ON audit_logs(created_at);